# Generated by Django 3.1.4 on 2021-01-25 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pic', models.ImageField(blank=True, upload_to='profile_pic')),
                ('phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ShelfPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('image', models.ImageField(upload_to='shelfphotos/%Y/%m/%d')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('is_published', models.BooleanField(default=False)),
                ('is_ad', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_wheel_set', to='business.business')),
                ('members', models.ManyToManyField(to='business.Business')),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_published', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_shelf_set', to='business.business')),
                ('photos', models.ManyToManyField(blank=True, to='business.ShelfPhoto')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('pic', models.ImageField(upload_to='music/cover')),
                ('date', models.DateTimeField(auto_now=True)),
                ('music', models.FileField(default=True, upload_to='music/%Y/%m/%d')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_media_set', to='business.business')),
            ],
        ),
        migrations.CreateModel(
            name='Endorsement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_endorsements_set', to='business.business')),
                ('endorsers', models.ManyToManyField(to='business.Business')),
            ],
        ),
    ]
