# Generated by Django 3.1.4 on 2021-01-26 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelfphoto',
            name='price',
            field=models.CharField(max_length=70),
        ),
    ]
