# Generated by Django 3.1.4 on 2021-01-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20210128_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endorsement',
            name='endorsers',
            field=models.ManyToManyField(blank=True, related_name='endorsers', to='business.Business'),
        ),
        migrations.AlterField(
            model_name='endorsement',
            name='endorses',
            field=models.ManyToManyField(blank=True, related_name='endorses', to='business.Business'),
        ),
    ]
