# Generated by Django 3.1.4 on 2021-03-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20210128_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='pic',
            field=models.ImageField(blank=True, upload_to='music/cover'),
        ),
        migrations.AlterField(
            model_name='media',
            name='played',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
